FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package*.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

RUN npm run db:generate

RUN npm run build --filter=user-app

EXPOSE 3001

CMD ["npm","run","start-user-app"]
